#!/usr/bin/env python3
"""SmartPatrol — REAL app-data generator (kills the mock layer).
Reads ONLY the pipeline artifacts in reports/parkwatch/ (each computed from the
298,450-row BTP CSV by parkwatch_prep.py) and emits a single type-correct TS
module the React app imports. Every value the app renders is now real and
traceable. Run AFTER parkwatch_prep.py. Output: audit_v1/project/src/data/appData.ts
"""
import json, os

PW = "reports/parkwatch"
OUT = "audit_v1/project/src/data/appData.ts"

def load(name):
    with open(os.path.join(PW, name)) as f:
        return json.load(f)

vr = load("verification_report.json")
stations = load("stations.json")
hotspots = load("hotspots.geojson")
roster = load("roster.json")
watchlist = load("watchlist.json")
harm = load("harm_reorder.json")
timing = load("coverage_timing.json")

# ---- verification: add rows_dropped + clean date_window to the type shape ----
win = vr["date_window"]
lo, hi = [p.strip()[:10] for p in win.split("..")]
verification = {
    "rows_total": vr["rows_total"],
    "rows_dropped": vr["rows_total"] - vr["rows_in_bbox"],   # 298450 - 298282 = 168 (bbox + coerce)
    "date_window": f"{lo} .. {hi}",
    "pct_rows_with_roadclass_label": vr["pct_rows_with_roadclass_label"],
    "n_cells": vr["n_cells"],
    "cells_for_50pct_volume": vr["cells_for_50pct_volume"],
    "top100_cells_pct": vr["top100_cells_pct"],
    "random100_cells_pct": vr["random100_cells_pct"],
    "patrol_efficiency_x": vr["patrol_efficiency_x"],
    "n_stations": vr["n_stations"],
    "stations_for_50pct": vr["stations_for_50pct"],
    "stations_for_80pct": vr["stations_for_80pct"],
    "offenders_ge10": vr["offenders_ge10"],
    "offenders_ge5": vr["offenders_ge5"],
    "max_violations_single_vehicle": vr["max_violations_single_vehicle"],
    "top_vehicle_stations": vr["top_vehicle_stations"],
    "chronic_across_ge2_stations": vr["chronic_across_ge2_stations"],
    "chronic_across_ge3_stations": vr["chronic_across_ge3_stations"],
    "systemic_across_ge2_stations": vr["systemic_across_ge2_stations"],
    "systemic_across_ge3_stations": vr["systemic_across_ge3_stations"],
    "systemic_across_ge4_stations": vr["systemic_across_ge4_stations"],
    "top142_temporal_stability_pct": vr["top142_temporal_stability_pct"],
    "cells_promoted_by_harm_top142": vr["cells_promoted_by_harm_top142"],
    "harm_vs_volume_spearman": vr["harm_vs_volume_spearman"],
}

# ---- hotspots: keep a clean, meaningful marker set (top-60 by volume + every
#      harm-promoted corner) so the map shows real corners without 200-pin clutter ----
feats = [f for f in hotspots["features"]
         if f["properties"]["rank_volume"] <= 60 or f["properties"]["promoted_by_harm"]]
hotspots_out = {"type": "FeatureCollection", "features": feats}

# ---- roster: real greedy max-cover for ALL stations + citywide; cite canonical MCLP ----
roster_out = {
    "stations": roster["stations"],
    "citywide": roster["citywide"],
    "milp_prior_art": [
        "Church & ReVelle (1974), Maximal Covering Location Problem",
        "Marsh & Schilling (1994), Equity measurement in facility location",
    ],
    "equity_note": (
        "Solutions are computed per-station via greedy maximal-covering (1-1/e guarantee) over "
        "~150m beats; each picked beat is a real patrol location. Smaller jurisdictions are solved "
        "independently so they are never starved of units."
    ),
}

# ---- coverage-by-station-K: REAL, derived from roster.json's own-volume coverage ----
cbsk = {s: {K: round(sol["coverage_pct_of_station"], 1) for K, sol in sols.items()}
        for s, sols in roster["stations"].items()}

DATA = {
    "verification": verification,
    "stations": stations,
    "hotspots": hotspots_out,
    "roster": roster_out,
    "watchlist": watchlist,
    "harmReorder": harm,
    "coverageTiming": timing,
    "coverageByStationK": cbsk,
}

HEADER = """/* =============================================================================
 * SmartPatrol — REAL DATA (the "API" layer)
 * AUTO-GENERATED by src/parkwatch_app_data.py from reports/parkwatch/*.json —
 * each artifact computed from the 298,450-row BTP CSV by src/parkwatch_prep.py.
 * Every value rendered by the app is real and traceable. Do not hand-edit;
 * re-run the generator to refresh. (Replaces the former mockData.ts.)
 * ===========================================================================*/
import type {
  Verification, Stations, Hotspots, Roster, Watchlist, HarmReorder,
  CoverageTiming, CoverageByStationK,
} from "../types";

"""

EXPORTS = [
    ("verification", "Verification"),
    ("stations", "Stations"),
    ("hotspots", "Hotspots"),
    ("roster", "Roster"),
    ("watchlist", "Watchlist"),
    ("harmReorder", "HarmReorder"),
    ("coverageTiming", "CoverageTiming"),
    ("coverageByStationK", "CoverageByStationK"),
]

ts = HEADER
for name, typ in EXPORTS:
    ts += f"export const {name} = ({json.dumps(DATA[name], ensure_ascii=False)}) as unknown as {typ};\n\n"

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write(ts)

print("wrote", OUT, f"({os.path.getsize(OUT)//1024} KB)")
print("verification.rows_dropped =", verification["rows_dropped"], "| date_window =", verification["date_window"])
print("hotspot markers:", len(feats), "| roster stations:", len(roster_out["stations"]),
      "| coverageByStationK:", len(cbsk), "| offenders:", len(watchlist["offenders"]),
      "| graph vehicles:", list(watchlist["graph"].keys()))
print("phantom FKN00GL03377 present?:", any(o["vehicle"] == "FKN00GL03377" for o in watchlist["offenders"]))
